name: Slash

on:
  push:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v1
      - uses: BSFishy/meson-build@v1.0.3
        with:
          action: build
          directory: build
